export const environment = {
  production: false,
  API_URL:  "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxYzRlMzZjMTcwODc0M2M2ODkyOWY3YzVjMzgyYjFmYSIsInN1YiI6IjY0ZjhhZWY5YThiMmNhMDBmZWRkOTZkOCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.2u6wcaLA9ML5PjtfNs5W4jFqSFrqBaz4QZSv_ftPbrY",
};